version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: orchestrator-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - orchestrator-network

  # Orchestrator Service
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orchestrator-service
    environment:
      # Database
      DATABASE_URL: "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza182UmpKQmNCSVdvRi1iZWNiZDVGbmwiLCJhcGlfa2V5IjoiMDFLNjRXUDI3OFNROTUxQTlHN1JHVDNQSjciLCJ0ZW5hbnRfaWQiOiIyYjcwYzNmZmNhODQ1ZDQ1NWJhZjBkYTdiM2ExMjczMGFmNDFjZDAxMWRiZmJkM2QwYjAyZWExZGRkZGJiZTdjIiwiaW50ZXJuYWxfc2VjcmV0IjoiMzNmMThjMjktZmJkMS00YTZhLWE0ZmYtYmJlN2ZmOGFkNTY3In0.URNVO5xVxOq3H7DdY6cGdGk9Ll6_m2wE_4dGSF8qsBc"
      
      # AWS KMS (configure with your actual values)
      AWS_REGION: "us-east-1"
      KMS_KEY_ID: "arn:aws:kms:us-east-1:343218204518:key/f2d33a32-b3dd-4f02-8b0d-c4c0c71f0c4a"
      
      # Chain Configuration (update with actual RPCs)
      KADENA_EVM_CHAIN_5920_RPC: "http://127.0.0.1:8545/chain/0/evm/rpc"
      KADENA_EVM_CHAIN_5921_RPC: "http://127.0.0.1:8545/chain/1/evm/rpc"
      KADENA_EVM_CHAIN_5922_RPC: "http://127.0.0.1:8545/chain/2/evm/rpc"
      KADENA_EVM_CHAIN_5923_RPC: "http://127.0.0.1:8545/chain/3/evm/rpc"
      KADENA_EVM_CHAIN_5924_RPC: "http://127.0.0.1:8545/chain/4/evm/rpc"
      
      # Contract Addresses (update with actual addresses)
      STABLECOIN_CONTRACT_ADDRESS_5920: "0x948B3c65b89DF0B4894ABE91E6D02FE579834F8F"
      STABLECOIN_CONTRACT_ADDRESS_5921: "0x948B3c65b89DF0B4894ABE91E6D02FE579834F8F"
      STABLECOIN_CONTRACT_ADDRESS_5922: "0x948B3c65b89DF0B4894ABE91E6D02FE579834F8F"
      STABLECOIN_CONTRACT_ADDRESS_5923: "0x948B3c65b89DF0B4894ABE91E6D02FE579834F8F"
      STABLECOIN_CONTRACT_ADDRESS_5924: "0x948B3c65b89DF0B4894ABE91E6D02FE579834F8F"
      
      KYC_REGISTRY_CONTRACT_ADDRESS_5920: "0x8464135c8F25Da09e49BC8782676a84730C318bC"
      
      # Relayer Private Keys (update with actual keys - use secrets in production)
      RELAYER_PRIVATE_KEY_5920: "0x1234567890123456789012345678901234567890123456789012345678901234"
      RELAYER_PRIVATE_KEY_5921: "0x1234567890123456789012345678901234567890123456789012345678901234"
      RELAYER_PRIVATE_KEY_5922: "0x1234567890123456789012345678901234567890123456789012345678901234"
      RELAYER_PRIVATE_KEY_5923: "0x1234567890123456789012345678901234567890123456789012345678901234"
      RELAYER_PRIVATE_KEY_5924: "0x1234567890123456789012345678901234567890123456789012345678901234"
      
      # Kuro Service Configuration
      KURO_WEBSOCKET_URL: "ws://kuro-mock:8080/events"
      KURO_REST_URL: "http://kuro-mock:8080/api"
      
      # Redis
      REDIS_URL: "redis://redis:6379"
      
      # Server
      PORT: "3000"
      NODE_ENV: "production"
      LOG_LEVEL: "info"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - orchestrator-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health/live', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Kuro Mock Service (for testing)
  kuro-mock:
    image: node:18-alpine
    container_name: kuro-mock
    working_dir: /app
    command: >
      sh -c "
        npm install express ws &&
        node -e \"
          const express = require('express');
          const WebSocket = require('ws');
          const app = express();
          
          app.use(express.json());
          
          // REST endpoint
          app.get('/api/mint-requests/pending', (req, res) => {
            res.json([]);
          });
          
          app.listen(8080, () => console.log('Kuro mock REST server running'));
          
          // WebSocket server
          const wss = new WebSocket.Server({ port: 8081 });
          console.log('Kuro mock WebSocket server running');
        \"
      "
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - orchestrator-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  orchestrator-network:
    driver: bridge